### ISSUE TITLE
Add a config option to not shorten UMF messages

### ISSUE THREAD

**Issue by paulwaksmonski** [flywheelsports/hydra#136]
This would be useful where message sizes do not need to be small.

**Comment by cjus** [comment]
@paulwaksmonski definitely this is an area that needs work. I also don't love the ideal of switching back and forth between short and long form UMF messages. The issue I have with config files is that the behavior can be different between microservices and even instances of a particular microservice potentially leading to interoperability problems.  At some level perhaps switching completely to short form might be the solution.

**Comment by cjus** [comment]
This is currently by designed and won't be fixed.
