### ISSUE TITLE
How to add new services with out restarting API gateway /hydra-router?

### ISSUE THREAD

**Issue by techwizardg** [flywheelsports/hydra#138]
This is not a bug but not sure where to ask? How do i add new microservices in hydra with out restarting API gateway or hydra-router?

**Comment by cjus** [comment]
@techwizardg when a hydra-enabled service starts it tries to send broadcasts a message to listening hydra-router (if any) and at that point new / changed routes are updated. So if this isn't working for you it's a bug. As a work-around for now - you can send a message to a hydra-router to update it's known routes using: http://localhost:5353/v1/router/refresh.
