### ISSUE TITLE
findService() returns incomplete object

### ISSUE THREAD

**Issue by tolik93** [flywheelsports/hydra#139]
Hello, 
i am trying to use hydra in my project. I wanna get ip address and port of service. 
hydra.findService('test-service') returns an object with only 3 properties: 
{"serviceName":"test-service","type":"","registeredOn":"2017-07-21T11:25:14.530Z"}

How can I get ip and port?

Thx

**Comment by cjus** [comment]
@tolik93 see: getServicePresence : https://www.hydramicroservice.com/docs/hydra-core/hydra-methods.html

**Comment by tolik93** [comment]
@cjus Thank you. I missed this method
