### ISSUE TITLE
How to view hydra key-value pairs in native redis cli ??

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [flywheelsports/hydra#141]
Firstly, thank you for awesome module. 

I know using hydra-cli , I can get total list of nodes,routes etc . I'm curious how hydra really use redis to store this key-value pair.

Once everything up and running, I tried view hydra service related registries in redis server using redis-cli, but unable to see anything ?? Is there any best approach?

Regards,
Sai.

**Comment by cjus** [comment]
@skalyanapu-mtuity Thank you for trying Hydra!

When you connect to redis make sure to select database 15 or which ever redis database you're using.

```
select 15
```

You should see keys there. Also I recommend trying Medis if you're using a mac: http://getmedis.com/

**Comment by skalyanapu-mtuity** [comment]
@cjus Yes! I missed it.
Thank you !!

**Comment by cjus** [comment]
@skalyanapu-mtuity no worries - thanks again for trying Hydra!
