### ISSUE TITLE
How to integrate with Netflix Eureka?

### ISSUE THREAD

**Issue by danielsan** [flywheelsports/hydra#147]
Hi everyone,

I'm trying to choose a microservices framework to use with node
but I really need to be able to integrate it with Eureka since we already have a
microservices infrastructure using Eureka :'(

Does anybody know how one could integrate hydra with Eureka for service register/discovery?

I don't necessarily want to make the hydra microservices to discover each other using Eureka.
I want the possibility to register to it and to eventually use services that are out of the hydra microservices network.

**Comment by cjus** [comment]
@danielsan I recommend you also post in our Slack group: https://fwsp-hydra.slack.com

**Comment by cjus** [comment]
@danielsan can I close this or should we label it help wanted?
