### ISSUE TITLE
SWIM membership protocol integration ??

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [flywheelsports/hydra#160]
Hi @cjus,

Instead of centralized services registry using, how about the integration SWIM membership protocol.
  - Though we create Redis cluster services registries and load balance them, which involves again resource 
     consumption and network hops.
  - Pattern matching, with no or minute dependency with location of the other MS, when there are being    
    called by another MS.
  - How matured in logging ??
  - Does Hydra was production ready ?? 
 
How far Hydra has these features ??If not is there plans for implementation?

Regards,
Sai.

**Comment by cjus** [comment]
Hello @skalyanapu-mtuity 

Good questions. Hydra is indeed production ready - as defined by companies which are successfully and significantly using Hydra in their own production environments. And there are perhaps more companies which use Hydra in smaller less critical areas of their infrastructure.

There are currently no plans to move away from Redis.  To be honest I see Hydra forking if it were to do so. And I don't see that as a bad thing.  We feel there's a strong usecase for Hydra as it stands.

Hydra has a very mature logging plugin based on Pino /logstash.
https://www.npmjs.com/package/fwsp-logger

Have you looked at SenecaJS? http://senecajs.org/  It supports patterns and has SWM integration I believe.

Richard Rodger discusses it here: https://www.youtube.com/watch?v=67POODXANi8

@skalyanapu-mtuity do you have a usecase where the things you're asking would be a serious deciding factor on whether or not to use Hydra? If so we'd like to better understand your needs.

**Comment by skalyanapu-mtuity** [comment]
Hi @cjus ,

We referred Seneca , before coming here. Hydra looks more flexible in creation  of MS and maintenance than Seneca , few things we're looking for were does , Hydra have 

 - SWIM compatibility , (you answered already) actually impressed with Richard Rodger's effort towards SWIM integration, which reduces extra overhead and maintenance of  exclusive service registry.
- We already some MS in Spring boot , using Eureka , can we integrate Eureka with Hydra router ??
- Very matured logging.
- Circuit break mechanism.
- Node JS 8 / Typescript compatibility -- Promises, Async 
- Very strong auth libraries.
- Seamless communication b/w MS.

These are some points we're considering right now , @cjus  could you please your inputs ??

Regards,
Sai.

**Comment by cjus** [comment]
@skalyanapu-mtuity sorry for the delay. We've just launched a major product at work. Hydra is a low-level library and many of the things you're looking for can be added as plugins.  For example, auth libraries, logging and promises / async etc...  We're currently focused on optimizations to Hydra but welcome community contributions.
