### ISSUE TITLE
How to send UFM message from non-hydra server to hydra micraservice?

### ISSUE THREAD

**Issue by emjimadhu** [flywheelsports/hydra#173]
HI all, First of all thanks for this awesome service. 

I have a expressjs app (non hydra), and two microservice (hydra-express). i want to send a request to microservice from express app. i tried sample message from documentation. but it gives error. can you guys point me out how to implement message from non-hydra app to hydra microservice?

**Comment by sjmcdowall** [comment]
Hello Em Ji Madhu!

I am new to this as well, so this could be a good learning experience as I try to understand all the magic here too!  :) 

From all the documentation I have read what you want to do should be pretty easy so that is good! 

Can you share the code you are using to try to invoke the service and the output from when you run the service (it has nice information) and of course what actual error code are you getting?  

You can also try to access the service from the command line via “curl” — have you tried that? 

Cheers!

/Steve

**Comment by cjus** [comment]
@emjimadhu You can simply send an HTTP RESTful request from an expressjs app to any hydra-express app which has exposed an endpoint.  The body of that message (assuming POST) can be a UMF message. Sending messages between hydra/hydra-express apps only needs the hydra.sendMessage call.

If you'd like to send websocket messages to hydra-express apps from other services you can also do that via our Hydra-Router service. See: https://www.hydramicroservice.com/docs/tools/hydra-router/

If you'd like to engage with others using Hydra consider joining our Slack channel. More info here: https://github.com/flywheelsports/hydra#join-us-on-slack

**Comment by cjus** [comment]
@emjimadhu `serverName` cannot be blank.

**Comment by emjimadhu** [comment]
@cjus hey thank you for the reply. the server i am communicating from is not a service. just like it said in the below image, i made it blank. or am i understood wrong.

![screenshot from 2018-02-17 11-30-29](https://user-images.githubusercontent.com/15604962/36338484-44c343b8-13d6-11e8-9810-c59fd1ec9cb1.png)

if i am wrong, what i have to do next? my scenario is i have a server and i want to communicate with hydra microservice.

**Comment by cjus** [comment]
@emjimadhu I see. I also went back to take a closer look at your sample program above. So you're initializing hydra in an express route? and trying to use the hydra. findService call to locate the firebase-service?

I recommend initializing hydra in your app initialization (main js file) and then importing hydra in your route file using:

```
const hydra = require('hydra');
```

Then later you can call hydra.findService('firebase-service')

In the mean-time I'll write a small test program to ensure this still works and I'll share that with you.

**Comment by cjus** [comment]
@emjimadhu So there is an issue with the documentation or perhaps I'll fix in an updated hydra release. `serviceName` is required and can't currently be blank.  So here is a sample config.json file which does contain a serviceName.

```javascript
{
  "hydra": {
    "serviceName": "caller",
    "serviceDescription": "",
    "serviceIP": "",
    "servicePort": 0,
    "serviceType": "",
    "redis": {
      "url": "redis://localhost:6379/15"
    }
  }
}
```

This Sample program shows a basic express app which loads hydra and attempts to locate information about hydra-routers which may be loaded. In your case that would be your `firebase-service`.  In your earlier example you used the hydra.findService() call. But I think you probably need to use the hydra.getServicePresence() call which returns an array of all present service instances along with ip and port addresses.  At the end of this post I shared the output of the program below.

```javascript
const express = require('express');
const app = express();
const hydra = require('hydra');
const config = require('./config.json');

app.get('/', (req, res) => res.send('Hello World!'));
app.listen(3000, () => console.log('Example app listening on port 3000!'));

hydra.init(config)
  .then(() => {
    console.log('hydra initiated');
    return hydra.getServicePresence('hydra-router');
  })
  .then((service) => {
    console.log(service);
  })
  .catch((error) => {
    console.log(error)
  });
```

Output: 

```
Array(1) [Object]
index.js:15
length:1
__proto__:Array(0) [, …]
0:Object {serviceName: "hydra-router", serviceDescription: "Service Router", version: "1.6.0", …}
  hostName:"AdministorsMBP2.fios-router.home"
  instanceID:"46bb1d0037264eb0898adde39cdd257e"
  ip:"192.168.1.221"
  port:1552
  processID:10750
  serviceDescription:"Service Router"
  serviceName:"hydra-router"
  updatedOn:"2018-02-19T03:55:52.114Z"
  updatedOnTS:1519012552114
  version:"1.6.0"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}
```

**Comment by emjimadhu** [comment]
@cjus Thank you so much. It worked.

**Comment by cjus** [comment]
You're welcome! I'm closing out this issue.
