### ISSUE TITLE
_checkServicePresence throws a reject although it says it will never do so

### ISSUE THREAD

**Issue by sjmcdowall** [flywheelsports/hydra#176]
https://github.com/flywheelsports/hydra/blob/master/index.js#L941

According to the "contract" this method should never throw a reject() -- yet it does here:

https://github.com/flywheelsports/hydra/blob/master/index.js#L973

**Comment by cjus** [comment]
@sjmcdowall correct. ;-) Doc should be corrected to reflect what really happens.

**Comment by sjmcdowall** [comment]
Fixed by pr # 181
