### ISSUE TITLE
Various improvements possible in mocha test cases

### ISSUE THREAD

**Issue by sjmcdowall** [flywheelsports/hydra#178]
1 -- There appear to be 3 duplicate tests in test.js 
https://github.com/sjmcdowall/hydra/blob/master/specs/test.js#L182
https://github.com/sjmcdowall/hydra/blob/master/specs/test.js#L239

https://github.com/sjmcdowall/hydra/blob/master/specs/test.js#L198
https://github.com/sjmcdowall/hydra/blob/master/specs/test.js#L255

https://github.com/sjmcdowall/hydra/blob/master/specs/test.js#L219
https://github.com/sjmcdowall/hydra/blob/master/specs/test.js#L276

2 -- Inconsistent use of @description vs. @summary 

3 -- No code coverage report appears to be generated.  This could be a good thing to see?

**Comment by cjus** [comment]
Cut and paste no doubt. PR?

**Comment by sjmcdowall** [comment]
Fixed by https://github.com/flywheelsports/hydra/pull/180
