### ISSUE TITLE
A warning about storing application data in the same Redis db as Hydra metadata

### ISSUE THREAD

**Issue by rantecki** [flywheelsports/hydra#192]
I've just learned the hard way that it is NOT a good idea to mix your application data with Hydra's data in the default Redis database (db 0) if your services generate a lot of keys.

I've just spent an entire day trying to get to the bottom of very puzzling performance issues of a large system we launched a few days ago.  As the number of keys in Redis kept climbing, the system got slower and slower until the point that it was unusable.  After a lot of digging, it turned out that the `SCAN MATCH` command used by Hydra's `checkPresence()` function was the culprit.  Apparently `SCAN MATCH` will iterate through the entire keyspace looking for a needle in a haystack.  With a database of 100,000+ keys, that's 1000+ scan calls needed just to check service presence (with chunk size of 100).  It easily took an R4.large Elasticache instance to its knees under moderate client load.  Moving the app data out to a separate db immediately solved the issue.

Perhaps it wouldn't be a bad idea to add a prominent note to the docs somewhere about this situation, to save some other people a world of pain.

Heed my warnings!

**Comment by sjmcdowall** [comment]
Very interesting — and yes, I would think it would always be a pretty good to isolate such different work loads.

However, it does make me wonder if there isn’t some inherent performance issue with checkPresence itself as well.  That behavior sounds odd (the high on the resources) under load…

**Comment by cjus** [comment]
@rantecki thanks for your investigation and post!  The issue you discovered is true of any Redis command that matches. `keys` is particularly bad in that context.

We learned of that issue early on and ALWAYS choose Redis DB #15 to store hydra keys.  Also, we're moving towards using a dedicated Redis cluster for Hydra and let our microservices use another Redis cluster if they need Redis functionality. This information will part of my RedisConf18 presentation and I'll also update our documentation to highlight this issue.

**Comment by rantecki** [comment]
Yes, well I guess my thought process was that Hydra's already doing all the hard work in connecting to Redis, so I'd just piggyback off that and use the same connection.  It saved me some time when building the initial prototype.

Anyway, now that that's been sorted out the whole thing is running pretty smoothly now, so well done for building such a great platform.
