### ISSUE TITLE
Disable redis connection

### ISSUE THREAD

**Issue by leonardorifeli** [flywheelsports/hydra#207]
I'm using hydra to a single small gateway API.
How to I disable redis connection? Do that's possible?
Thanks.

**Comment by emadum** [comment]
You could use [redis-mock](https://www.npmjs.com/package/redis-mock).

**Comment by leonardorifeli** [comment]
Thanks, @emadum. But, to use redis-mock only, you can set `testMode: true` on properties file.

My properties file:

```js
exports.value = {
	cluster: false,
	maxSockets: 500,
	environment: process.env.NODE_ENV || 'development',
	testMode: true, //here
	logPath: '',
	logRequestHeader: true,
	logOutboundRequest: true,
	hydra: {
		serviceName: 'api-name',
		serviceDescription: 'API',
		serviceIP: '',
		servicePort: 8000,
		serviceType: 'test',
		redis: {}
	}
};
```
