### ISSUE TITLE
Documentation links to the Slack team for flywheelsports which is password protected

### ISSUE THREAD

**Issue by jedsmithobd** [flywheelsports/hydra#46]
The documentation has a link to Slack that requires a sign in to join. It is great to have a slack channel to talk about Hydra, but it would be even better if I could join the discussions ;)

**Comment by cjus** [comment]
@jedsmithobd not sure how to open Slack up to just allows signup. But if you send me an email at cjus34@gmail.com I'll send you an invite.

**Comment by jedsmithobd** [comment]
I think I have seen a slack auto invite that a colleague used for his slack channel. I will see if I can find the link for you.

**Comment by cjus** [comment]
I did see that too, but it seemed to be tied to domain names. @jedsmithobd saw your email, I'll add you manually. You should see an invite soon.

**Comment by jedsmithobd** [comment]
I found an example of what I was looking for. [https://github.com/outsideris/slack-invite-automation](https://github.com/outsideris/slack-invite-automation). It is basically a simple server that lets an individual enter an email and then automatically sends them an invite.

It also looks like it can be deployed to Heroku or Azure to make it even easier to implement.

**Comment by cjus** [comment]
Closing for now. Until we have time to implement this.
