### ISSUE TITLE
Throw exception if already initialized.

### ISSUE THREAD

**Issue by cjus** [flywheelsports/hydra#5]
Hydra should throw an exception if already initialized.

**Comment by sjmcdowall** [comment]
Lol I just working on this!!

**Comment by sjmcdowall** [comment]
Can be closed -- fixed by PR#185

**Comment by sjmcdowall** [comment]
@cjus -- Really can close this again as fixed..  :)

**Comment by sjmcdowall** [comment]
Really really can be closed @cjus :)
